Repository Synapxe-DNA/technical-docs, pull requests merged in 2024-07, with the labels that each got.

#1 Added docs for mongo_connector
  docs/backend/db/mongo_connector.md
  mkdocs.yml
Labels: documentation

#2 Added docs for types
  .github/workflows/ci.yml
  docs/backend/api/endpoints.md
  docs/backend/ideology.md
  docs/backend/index.md
  docs/blog/index.md
  docs/blog/posts/7-git-tips-to-overcome-your-fear-of-version-control.md
  docs/projects/genai/example-project/section-one/index.md
  docs/projects/genai/example-project/section-one/introduction.md
  docs/projects/genai/example-project/section-two/index.md
  docs/projects/genai/example-project/section-two/introduction.md
  docs/projects/genai/health-hub/content-harmonization/index.md
  docs/projects/genai/health-hub/content-harmonization/introduction.md
  docs/projects/genai/health-hub/content-optimization/index.md
  docs/projects/genai/health-hub/content-optimization/introduction.md
  docs/projects/genai/health-hub/webapp/backend/api/endpoints.md
  docs/projects/genai/health-hub/webapp/backend/api/endpoints.yaml
  docs/projects/genai/health-hub/webapp/backend/api/route_organisation.md
  docs/projects/genai/health-hub/webapp/backend/db/db_connector.md
  docs/projects/genai/health-hub/webapp/backend/db/mongo/beanie_documents.md
  docs/projects/genai/health-hub/webapp/backend/db/mongo/mongo_connector.md
  docs/projects/genai/health-hub/webapp/backend/introduction.md
  docs/projects/genai/health-hub/webapp/backend/types/articles/article.md
  docs/projects/genai/health-hub/webapp/backend/types/articles/article_meta.md
  docs/projects/genai/health-hub/webapp/backend/types/articles/article_status.md
  docs/projects/genai/health-hub/webapp/backend/types/articles/generated_article.md
  docs/projects/genai/health-hub/webapp/backend/types/jobs/job.md
  docs/projects/genai/health-hub/webapp/backend/types/jobs/job_combine.md
  docs/projects/genai/health-hub/webapp/backend/types/jobs/job_ignore.md
  docs/projects/genai/health-hub/webapp/backend/types/jobs/job_optimise.md
  docs/projects/genai/health-hub/webapp/backend/types/jobs/job_remove.md
  docs/projects/genai/health-hub/webapp/backend/types/overview.md
  docs/projects/genai/health-hub/webapp/backend/types/relations/edge.md
  docs/projects/genai/health-hub/webapp/backend/types/relations/group.md
  docs/projects/genai/health-hub/webapp/introduction.md
  docs/projects/genai/health-hub/webapp/system_architecture.md
  mkdocs.yml
Labels: documentation, enhancement

#5 Major rehaul
  .gitattributes
  .github/workflows/lint.yml
  .github/workflows/prettier-markdown-check.yml
  .github/workflows/publish.yml
  .gitignore
  .markdownlint.jsonc
  .pre-commit-config.yaml
  LICENSE
  Makefile
  README.md
  docs/blog/.authors.yml
  docs/blog/index.md
  docs/blog/posts/7-git-tips-to-overcome-your-fear-of-version-control.md
  docs/blog/posts/sentence-transformers-for-sentence-similarity.md
  docs/index.md
  docs/projects/genai/example-project/section-one/index.md
  docs/projects/genai/example-project/section-one/introduction.md
  docs/projects/genai/example-project/section-two/index.md
  docs/projects/genai/example-project/section-two/introduction.md
  docs/projects/genai/health-hub/content-harmonization/index.md
  docs/projects/genai/health-hub/content-harmonization/introduction.md
  docs/projects/genai/health-hub/content-optimization/index.md
  docs/projects/genai/health-hub/content-optimization/introduction.md
  docs/projects/genai/health-hub/webapp/intro.md
  mkdocs.yml
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement

#6 Added example Jupyter notebook
  .github/workflows/publish.yml
  Makefile
  docs/projects/genai/example-project/section-one/tfidf_max_features_384_cosine_emd.ipynb
  mkdocs.yml
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement

#7 Fixed github actions
  .github/workflows/publish.yml
  pyproject.toml
  requirements.txt
Labels: bug

#9 Optimized and combined github actions
  .github/workflows/checks.yml
  .github/workflows/lint.yml
  .github/workflows/prettier-markdown-check.yml
Labels: enhancement

#12 Updated `README.md` and GitHub Actions
  .github/workflows/publish-documentation.yml
  .github/workflows/run-checks.yml
  Makefile
  README.md
Labels: documentation, enhancement

#11 Styling fixes
  docs/projects/genai/health-hub/webapp/backend/types/overview.md
  docs/styles/mermaid.css
  mkdocs.yml
Labels: enhancement

#13 Updated `requirements.txt` and GitHub Actions for MkDocs Deployment
  .github/workflows/publish-documentation.yml
  .pre-commit-config.yaml
  README.md
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: documentation, enhancement

#15 Updated `pre-commit-config`, GitHub Actions and Project Documentation
  .github/workflows/run-checks.yml
  .pre-commit-config.yaml
  docs/projects/genai/health-hub/content-harmonization/index.md
  docs/projects/genai/health-hub/content-optimization/index.md
  docs/projects/genai/health-hub/content-optimization/introduction.md
  docs/projects/genai/health-hub/data-pipeline/index.md
  docs/projects/genai/health-hub/data-pipeline/introduction.md
  mkdocs.yml
Labels: documentation, enhancement

#16 Added header for ER diagram
  docs/projects/genai/health-hub/webapp/backend/backend_ERD.md
Labels: documentation

#17 Bugfix for Prettier `toml` plugin
  .github/workflows/run-checks.yml
  .pre-commit-config.yaml
Labels: bug

#18 Added frontend services and pipes
  README.md
  docs/js/doculabels.js
  docs/projects/genai/health-hub/webapp/backend/db/mongo/beanie_documents.md
  docs/projects/genai/health-hub/webapp/backend/db/mongo/er_diagram.md
  docs/projects/genai/health-hub/webapp/backend/db/mongo/mocker.md
  docs/projects/genai/health-hub/webapp/backend/introduction.md
  docs/projects/genai/health-hub/webapp/frontend/introduction.md
  docs/projects/genai/health-hub/webapp/frontend/pipes/date.md
  docs/projects/genai/health-hub/webapp/frontend/services/cluster.md
  docs/projects/genai/health-hub/webapp/frontend/services/colour.md
  docs/projects/genai/health-hub/webapp/frontend/services/job.md
  docs/projects/genai/health-hub/webapp/frontend/utilities/group_manager.md
  docs/projects/genai/health-hub/webapp/misc/mocker.md
  docs/projects/genai/health-hub/webapp/misc/populator.md
  mkdocs.yml
Labels: enhancement

#20 Added authors, and renders doculabels in HTML
  docs/js/doculabels.js
  docs/projects/genai/health-hub/webapp/backend/api/endpoints.md
  docs/projects/genai/health-hub/webapp/backend/api/route_organisation.md
  docs/projects/genai/health-hub/webapp/backend/db/db_connector.md
  docs/projects/genai/health-hub/webapp/backend/db/mongo/beanie_documents.md
  docs/projects/genai/health-hub/webapp/backend/db/mongo/er_diagram.md
  docs/projects/genai/health-hub/webapp/backend/db/mongo/mongo_connector.md
  docs/projects/genai/health-hub/webapp/backend/introduction.md
  docs/projects/genai/health-hub/webapp/backend/types/articles/article.md
  docs/projects/genai/health-hub/webapp/backend/types/articles/article_meta.md
  docs/projects/genai/health-hub/webapp/backend/types/articles/article_status.md
  docs/projects/genai/health-hub/webapp/backend/types/articles/generated_article.md
  docs/projects/genai/health-hub/webapp/backend/types/jobs/job.md
  docs/projects/genai/health-hub/webapp/backend/types/jobs/job_combine.md
  docs/projects/genai/health-hub/webapp/backend/types/jobs/job_ignore.md
  docs/projects/genai/health-hub/webapp/backend/types/jobs/job_optimise.md
  docs/projects/genai/health-hub/webapp/backend/types/jobs/job_remove.md
  docs/projects/genai/health-hub/webapp/backend/types/overview.md
  docs/projects/genai/health-hub/webapp/backend/types/relations/edge.md
  docs/projects/genai/health-hub/webapp/backend/types/relations/group.md
  docs/projects/genai/health-hub/webapp/frontend/introduction.md
  docs/projects/genai/health-hub/webapp/frontend/pipes/date.md
  docs/projects/genai/health-hub/webapp/frontend/services/cluster.md
  docs/projects/genai/health-hub/webapp/frontend/services/colour.md
  docs/projects/genai/health-hub/webapp/frontend/services/job.md
  docs/projects/genai/health-hub/webapp/frontend/utilities/group_manager.md
  docs/projects/genai/health-hub/webapp/introduction.md
  docs/projects/genai/health-hub/webapp/misc/mocker.md
  docs/projects/genai/health-hub/webapp/misc/populator.md
  docs/projects/genai/health-hub/webapp/system_architecture.md
  docs/styles/author.css
  docs/styles/doculabels.css
  mkdocs.yml
  overrides/main.html
  pyscripts/__init__.py
  pyscripts/authors/__init__.py
  pyscripts/authors/authors.py
  pyscripts/doculabels/__init__.py
  pyscripts/doculabels/doculabels.py
  requirements.txt
Labels: enhancement

#19 Added frontend activity diagram
  docs/projects/genai/health-hub/webapp/frontend/frontend_activity_diagram.md
  mkdocs.yml
Labels: documentation

#21 Added frontend documentation for types
  docs/projects/genai/health-hub/webapp/frontend/types/article.md
  docs/projects/genai/health-hub/webapp/frontend/types/cluster.md
  docs/projects/genai/health-hub/webapp/frontend/types/edge.md
  docs/projects/genai/health-hub/webapp/frontend/types/groups.md
  docs/projects/genai/health-hub/webapp/frontend/types/sorter.md
  guides/README.md
  mkdocs.yml
Labels: enhancement
