Repository Synapxe-DNA/technical-docs, pull requests merged in 2024-08, with the labels that each got.

#25 Added frontend documentation for HealthierME 2.0 key services
  .markdownlint.jsonc
  docs/projects/genai/conversational-assistant/webapp/frontend/introduction.md
  docs/projects/genai/conversational-assistant/webapp/frontend/services/chat-message.md
  docs/projects/genai/conversational-assistant/webapp/frontend/services/conversation-broker.md
  docs/projects/genai/conversational-assistant/webapp/frontend/services/endpoint.md
  docs/projects/genai/conversational-assistant/webapp/frontend/services/voice-activity-detection.md
  mkdocs.yml
Labels: enhancement

#27 Frontend service documentation (HealthierME 2.0)
  docs/projects/genai/conversational-assistant/webapp/frontend/services/audio-player.md
  docs/projects/genai/conversational-assistant/webapp/frontend/services/preference.md
  mkdocs.yml
Labels: enhancement

#31 Optimization checks ij
  docs/projects/genai/health-hub/article-rewriting/Introduction.md
  docs/projects/genai/health-hub/article-rewriting/LLM_Observability.md
  docs/projects/genai/health-hub/article-rewriting/LangChain.md
  docs/projects/genai/health-hub/article-rewriting/LangGraph.md
  docs/projects/genai/health-hub/article-rewriting/img/phoenix_trace.png
  docs/projects/genai/health-hub/article-rewriting/optimisation-checks/Introduction.md
  docs/projects/genai/health-hub/article-rewriting/optimisation-checks/img/LLM_checks_chain.jpg
  docs/projects/genai/health-hub/article-rewriting/optimisation-checks/img/optimisation_checks_workflow.jpg
  docs/projects/genai/health-hub/article-rewriting/optimisation-checks/nodes/Content.md
  docs/projects/genai/health-hub/article-rewriting/optimisation-checks/nodes/Meta_Description.md
  docs/projects/genai/health-hub/article-rewriting/optimisation-checks/nodes/Title.md
  mkdocs.yml
Labels: documentation

#32 Merge Optimisation Checks documentation to main
  docs/projects/genai/health-hub/article-rewriting/Introduction.md
  docs/projects/genai/health-hub/article-rewriting/LLM_Observability.md
  docs/projects/genai/health-hub/article-rewriting/LangChain.md
  docs/projects/genai/health-hub/article-rewriting/LangGraph.md
  docs/projects/genai/health-hub/article-rewriting/img/checks_rewriting_workflow.jpg
  docs/projects/genai/health-hub/article-rewriting/img/phoenix_trace.png
  docs/projects/genai/health-hub/article-rewriting/optimisation-checks/Introduction.md
  docs/projects/genai/health-hub/article-rewriting/optimisation-checks/img/LLM_checks_chain.jpg
  docs/projects/genai/health-hub/article-rewriting/optimisation-checks/img/optimisation_checks_workflow.jpg
  docs/projects/genai/health-hub/article-rewriting/optimisation-checks/nodes/Content.md
  docs/projects/genai/health-hub/article-rewriting/optimisation-checks/nodes/Meta_Description.md
  docs/projects/genai/health-hub/article-rewriting/optimisation-checks/nodes/Title.md
  mkdocs.yml
Labels: documentation

#33 Updated Introduction.md
  docs/projects/genai/health-hub/article-rewriting/optimisation-checks/Introduction.md
  docs/projects/genai/health-hub/article-rewriting/optimisation-checks/img/LLM_checks_chain.jpg
Labels: documentation

#34 Cleaned documentation, removed example project, added introduction
  docs/assets/images/retrieval-augmented-generation-workflow.png
  docs/blog/posts/best-practices-in-retrieval-augmented-generation.md
  docs/index.md
  docs/projects/genai/example-project/section-one/index.md
  docs/projects/genai/example-project/section-one/introduction.md
  docs/projects/genai/example-project/section-one/tfidf_max_features_384_cosine_emd.ipynb
  docs/projects/genai/example-project/section-two/index.md
  docs/projects/genai/example-project/section-two/introduction.md
  mkdocs.yml
Labels: documentation, enhancement

#37 Added github actions
  .github/workflows/stale-bot.yml
  .github/workflows/validate-markdown.yml
Labels: enhancement

#39 Optimization checks
  README.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/compiler_node.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/content_guidelines_harmonisation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/content_guidelines_optimisation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/meta_desc_optimisation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/personality_evaluation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/readability_optimisation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/researcher_node.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/title_optimisation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/writing_guidelines_optimisation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article_content_preprocessing.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article_harmonisation_intro.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article_optimisation_intro.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-opt-check/index.md
  docs/projects/genai/health-hub/content-opt-and-harm/images/article_harmonisation_flow.jpg
  docs/projects/genai/health-hub/content-opt-and-harm/images/article_optimisation_flow.jpg
  mkdocs.yml
Labels: documentation

#43 Optimization checks jc
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/compiler_node.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/content_guidelines_harmonisation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/content_guidelines_optimisation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/meta_desc_optimisation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/title_optimisation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article_harmonisation_intro.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article_optimisation_intro.md
  docs/projects/genai/health-hub/content-opt-and-harm/index.md
  mkdocs.yml
Labels: documentation

#45 Optimization checks
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/compiler_node.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/content_guidelines_harmonisation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/content_guidelines_optimisation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/meta_desc_optimisation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/title_optimisation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article_harmonisation_intro.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article_optimisation_intro.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-opt-check/images/LLM_checks_chain.jpg
  docs/projects/genai/health-hub/content-opt-and-harm/article-opt-check/index.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-opt-check/nodes/content.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-opt-check/nodes/meta-description.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-opt-check/nodes/title.md
  docs/projects/genai/health-hub/content-opt-and-harm/index.md
  docs/projects/genai/health-hub/content-opt-and-harm/langgraph.md
  mkdocs.yml
Labels: documentation

#46 Add documentation on Data Processing Pipeline
  docs/projects/genai/health-hub/data-pipeline/data-processing.md
  docs/projects/genai/health-hub/data-pipeline/data_processing/articles_flagged_removal.md
  docs/projects/genai/health-hub/data-pipeline/data_processing/index.md
  docs/projects/genai/health-hub/data-pipeline/data_processing/nodes/add_data.md
  docs/projects/genai/health-hub/data-pipeline/data_processing/nodes/extract_data.md
  docs/projects/genai/health-hub/data-pipeline/data_processing/nodes/index.md
  docs/projects/genai/health-hub/data-pipeline/data_processing/nodes/map_data.md
  docs/projects/genai/health-hub/data-pipeline/data_processing/nodes/merge_data.md
  docs/projects/genai/health-hub/data-pipeline/data_processing/nodes/standardize_columns.md
  docs/projects/genai/health-hub/data-pipeline/index.md
  mkdocs.yml
Labels: documentation

#47 Optimization checks jc
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/readability_optimisation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article_content_preprocessing.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article_harmonisation_intro.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/index.md
  docs/projects/genai/health-hub/content-opt-and-harm/images/article_harmonisation_flow.jpg
  docs/projects/genai/health-hub/content-opt-and-harm/index.md
Labels: documentation

#48 Optimization checks
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article-rewriting-nodes/readability_optimisation.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article_content_preprocessing.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article_harmonisation_intro.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/index.md
  docs/projects/genai/health-hub/content-opt-and-harm/images/article_harmonisation_flow.jpg
  docs/projects/genai/health-hub/content-opt-and-harm/index.md
  docs/projects/genai/health-hub/content-opt-and-harm/langgraph.md
Labels: documentation

#50 Optimization checks
  docs/projects/genai/health-hub/content-opt-and-harm/article-generation/article_harmonisation_intro.md
  docs/projects/genai/health-hub/content-opt-and-harm/article-opt-check/index.md
  mkdocs.yml
Labels: documentation
